[package]
name = "arbitrary-code"
version = "0.1.0"
authors = ["Aofusa <5000enPCinAOFUSA@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
wasmtime = "0.21"
reqwest = { version = "0.10", features = ["blocking", "json"] }
clap = "2"
